### ISSUE TITLE
User: Profile

### ISSUE THREAD

**Issue by ingressive4good** [Ingressive-for-Good/I4G-OPENSOURCE-BACKEND-PROJECT-2022#10]
- User can view and edit there profile details
- User can edit (change profile picture)
- Account Details (Account Details must match name)
- Change Password
- Update Shipping details
- Delete Account

**Comment by Ann-tech** [comment]
I would like to work on this as well as the wishlist issue

**Comment by ingressive4good** [comment]
You have been assigned the issue @Ann-tech looking forward to your pull request

**Comment by Ann-tech** [comment]
Alright, on it

**Comment by ingressive4good** [comment]
@Ann-tech  what's the progress status on this?
