### ISSUE TITLE
User: Wishlist

### ISSUE THREAD

**Issue by pragmaticAweds** [Ingressive-for-Good/I4G-OPENSOURCE-BACKEND-PROJECT-2022#11]
- Users can add an item they view to their cart.
- Users can show interest in a product added to their cart.
- Users can delete products from their cart if they don't have an interest.
- Users can delete products from their cart if it is no more available.

**Comment by Ann-tech** [comment]
I would like to work on this issue

**Comment by funkycadet** [comment]
Have you started working on this issue @Ann-tech ?

**Comment by RealRichi3** [comment]
I would like to work on this issue

**Comment by RealRichi3** [comment]
@Ann-tech have you started working on this issue?

**Comment by Ann-tech** [comment]
You can work on the issue. I'll focus on the profile section

**Comment by Amidsts** [comment]
assign the issue to yourself, if are working on it

**Comment by RealRichi3** [comment]
Alright

**Comment by ingressive4good** [comment]
@RealRichi3 what's the progress status on this?
