### ISSUE TITLE
database schema

### ISSUE THREAD

**Issue by Amidsts** [Ingressive-for-Good/I4G-OPENSOURCE-BACKEND-PROJECT-2022#12]
User
    username
    firstname
    profilePicture
    lastname
    phoneNo
    password
    address
    isAdmin
   friends/follower

cart
  userId
  cartItems
  

chat
   senderId
   recieverId
  messages

Product
  userId
  productName
  description
  price
  productImage

**Comment by spykelionel** [comment]
I will love to tackle this
