### ISSUE TITLE
User: isLoggedIn middleware

### ISSUE THREAD

**Issue by ntekim** [Ingressive-for-Good/I4G-OPENSOURCE-BACKEND-PROJECT-2022#27]
Summary
-------

Allows only loggedIn users access to certain functionality of the app

Steps to reproduce
------------------

1. Check for authorization token - JWT token for example

2. Check if user exist with the _id gotten from the token

Expected result
---------------

1. If exist, then permission granted; 
2. else not allowed to perform action.

**Comment by ntekim** [comment]
@Ingressive-for-Good/i4g-opensource-challenge-2022

**Comment by Arndy345** [comment]
I wish to take on this issue

**Comment by codewithmide** [comment]
@ntekim is it fine with you, if we assign this issue to @Arndy345

**Comment by ntekim** [comment]
Yes, sure

**Comment by ingressive4good** [comment]
@ntekim what's the progress status on this?

**Comment by ntekim** [comment]
> @ntekim what's the progress status on this?

@ingressive4good Just opened a pull request that solves this issue

**Comment by spykelionel** [comment]
Check #47
