### ISSUE TITLE
User: support

### ISSUE THREAD

**Issue by EAZYLINK** [Ingressive-for-Good/I4G-OPENSOURCE-BACKEND-PROJECT-2022#28]
**Title**
Help and Support

**Summary**
Users should be able to seek help and support in case of challenge in accessing some features or issues with account by filling google form or accessing frequently asked question

**Environment**
Browser

Steps to reproduce

1.  Create an end point for users to access FAQs
2. Create an end point for users to fill out their issues on a google form if not answered on FAQs
3. Notify user after filling the google form that their issues will be responded via email

**Comment by Gerald-Izuchukwu** [comment]
Can I be assigned this?

**Comment by EAZYLINK** [comment]
Already working on it

**Comment by Gerald-Izuchukwu** [comment]
Alright mate, godspeed!

**Comment by ingressive4good** [comment]
@EAZYLINK what's the progress status on this

**Comment by EAZYLINK** [comment]
please reasign this issue
