### ISSUE TITLE
Authentication: Admin

### ISSUE THREAD

**Issue by ingressive4good** [Ingressive-for-Good/I4G-OPENSOURCE-BACKEND-PROJECT-2022#5]
- This is a protected route for super admin and admin
- Super admin have the over all access to the system
- Super Admin can invite other Admins by email

**Comment by izik4004** [comment]
I'd like to work on this

**Comment by ingressive4good** [comment]
I have assigned the task to you @izik4004

**Comment by ingressive4good** [comment]
@izik4004  what's the progress status on this?

**Comment by izik4004** [comment]
still working on it

**Comment by ingressive4good** [comment]
Please @izik4004 send in your PR as soon as possible
