### ISSUE TITLE
Refactor codebase

### ISSUE THREAD

**Issue by spykelionel** [Ingressive-for-Good/I4G-OPENSOURCE-BACKEND-PROJECT-2022#52]
I find difficulty understanding the current project structure. I propose the following changes 
Restructure project. 
- all controllers should be together
- all routes together
- all models together
- all auth strategy together

**Comment by Amidsts** [comment]
@spykelionel, the project is structured such that, anything related to users are together, anything related to product ll be together, and so on... the module folder is where that is taking place. But if this propsed structure is prefered, we can move the files from the modules folder to their respective folder then delete the modules folder 

what is your name on the telegram group ?

**Comment by spykelionel** [comment]
Telegram: [Spykelionel](t.me/spykelionel)
I understand what you mean, but I don't see it that way as of now. For example, the modules dir is has a lot of files which are not in their own folders (routes, controllers, and model)

**Comment by Amidsts** [comment]
The files are supposed to be inside their own folder, but I noticed they are not. I'm working on fixing it. 

I will message you on telegram

**Comment by spykelionel** [comment]
Alright 👍 @ORIYOMI289

**Comment by Amidsts** [comment]
@spykelionel the codebase has been refactor now
