### ISSUE TITLE
Products: Get product

### ISSUE THREAD

**Issue by Ayo-Awe** [Ingressive-for-Good/I4G-OPENSOURCE-BACKEND-PROJECT-2022#58]
- Get a product by id
- Fixes part of #51

**Comment by Ayo-Awe** [comment]
I'll begin working on this issue the moment #57 is merged to avoid merge conflicts

@dabsclement I've tried clicking the postman link, it's not working

**Comment by Amidsts** [comment]
@Ayo-Awe I will check the postman link again, but may I know what you meant by "fixes part", in this issue ? Before the issue is assign to you ?

**Comment by Ayo-Awe** [comment]
@ORIYOMI289 Sorry I meant that it solves a task on the main issue. The get product task in particular
