### ISSUE TITLE
Authentication: User - Signup

### ISSUE THREAD

**Issue by ingressive4good** [Ingressive-for-Good/I4G-OPENSOURCE-BACKEND-PROJECT-2022#6]
- User can sign up user the defined model fields
- User can sign up using Google 
- User email is verified and redirected to KYC 

KYC
- User fill the KYC form and choose ID type
- User phone number is verified and redirected to Login

**Comment by spykelionel** [comment]
Hello, which service is to be used for email verification and phone number verification?

I wish to take this issue

**Comment by dabsclement** [comment]
Any services we are using should be an open source service, I made a comment on the other issue you are interested in too. Join the project telegram group [here](https://t.me/+6um3V9A03YI3ODI0)

**Comment by spykelionel** [comment]
Okay thanks 👍

**Comment by ingressive4good** [comment]
@yasiramus what's is the status of this?

If you don't comment before the end of the day i will assign it to @spykelionel

**Comment by Goodness5** [comment]
Can we make use of Django for this?


I'm interested in this issue

**Comment by ikezuby2012** [comment]
I'm also interested in this issue

**Comment by ikezuby2012** [comment]
I'm also interested in this issue

**Comment by ingressive4good** [comment]
@yasiramus the project has been swithed back to javascript from typescript are you still interested in working on this?

**Comment by yasiramus** [comment]
Yes I am

**Comment by spykelionel** [comment]
@yasiramus what's the progress of this?
