### ISSUE TITLE
Authentication: User - Login

### ISSUE THREAD

**Issue by ingressive4good** [Ingressive-for-Good/I4G-OPENSOURCE-BACKEND-PROJECT-2022#7]
- User can login with there email and password
- sanitize the input using the expected characters
- Check if email and password is correct 
- Success

**Comment by spykelionel** [comment]
- I wish to take on this issue. Together with #6

**Comment by dabsclement** [comment]
Hello @spykelionel please hold on till Monday after the onboarding so that everyone can have a walk through the contribution procedure.

Thank you

**Comment by Wandji69** [comment]
Has this issue being assign?

**Comment by ingressive4good** [comment]
@spykelionel  what's the progress status on this?

**Comment by spykelionel** [comment]
Working on it. Almost done
