### ISSUE TITLE
User: Messages

### ISSUE THREAD

**Issue by ingressive4good** [Ingressive-for-Good/I4G-OPENSOURCE-BACKEND-PROJECT-2022#8]
- Users can send message another user
- Check if the user is logged in (only logged in user can message)
- Check the Frontend and design for more context

**Comment by ingressive4good** [comment]
@ntekim  what's the progress status on this?

**Comment by ntekim** [comment]
> @ntekim what's the progress status on this?

@Arndy345  volunteered and assigned it to himself, so don't know yet but if he is not available, I can get it done by the end of tomorrow

@ingressive4good
