### ISSUE TITLE
User: Product

### ISSUE THREAD

**Issue by pragmaticAweds** [Ingressive-for-Good/I4G-OPENSOURCE-BACKEND-PROJECT-2022#9]
- Users should be able to create products on their dashboard.
- Each product should have a reference id of the user who created it.
- Each product should also have a reference to whoever is interested in it.
- Product should have a category.
- Users should be able to delete a product.
- Users should be able to see who is interested in their product.

**Comment by Ayo-Awe** [comment]
@pragmaticAweds Are we creating a separate model for categories or we’re using enums

**Comment by dabsclement** [comment]
Enums will be better

**Comment by Timmy-id** [comment]
I think creating a category model will be fine as we don't know the number of categories that'll be available. 
Your thoughts @dabsclement?

**Comment by funkycadet** [comment]
About each product having a reference to whoever is interested in it, I'm not sure I understand what that means... Can anyone give some clarification to that? Thanks

**Comment by Timmy-id** [comment]
I don't think I understand that too @smith2eric 
@pragmaticAweds Please can you explain. Thank you.

**Comment by spykelionel** [comment]
I think all products users are interested in must réside in a cart. Everytime a product is being added the cart, boost the level or number of interest. @smith2eric ,@Timmy-id

**Comment by funkycadet** [comment]
Oh... Kind of like giving it a rating when users add it to cart or interact, is that what you mean? @spykelionel

**Comment by ingressive4good** [comment]
> 

category model should be created

**Comment by Timmy-id** [comment]
I think I get you now @pragmaticAweds

**Comment by Timmy-id** [comment]
I will like to work on this.

**Comment by spykelionel** [comment]
> I will like to work on this.

You can go on @Timmy-id

**Comment by spykelionel** [comment]
> > I will like to work on this.
> 
> You can go on @Timmy-id 

@Timmy-id Are you already working on this?

**Comment by Timmy-id** [comment]
Yes @spykelionel

**Comment by Timmy-id** [comment]
Hello @spykelionel Can you assign this to someone else as I am currently having issues with my laptop.

**Comment by ingressive4good** [comment]
@spykelionel  what's the progress status on this?

**Comment by spykelionel** [comment]
> @spykelionel what's the progress status on this?

In progress 👀
